spring:
  application:
    name: eureka-Server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 8080

management:
  security:
    enabled: false
